---
model:
  name: rnn
  hidden_size: 512
  dropout: 0.2
  recurrent_dropout: 0.2
  learning_rate: 0.001

data:
  max_digits: 4
  batch_size: 128
  train_size: 20000
  val_size: 512
  test_size: 1024
